# syntax=docker/dockerfile:1
FROM microsoft/dotnet:2.1-sdk
COPY . /app
WORKDIR /app
RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]
EXPOSE 1433
RUN chmod +x ./entrypoint.shis
CMD /bin/bash ./entrypoint.sh